### ISSUE TITLE
Stutter on changing devices

### ISSUE THREAD

**Issue by LeNitrous** [vignette-project/osu-framework-camera#2]
When changing devices the game freezes for a while.

**Comment by sr229** [comment]
I assume this is because the game loop is waiting on the device? That's not something we would want.

**Comment by LeNitrous** [comment]
Its certainly caused by these two lines.
https://github.com/holotrack/osu-framework-camera/blob/5d2151a34d017740c72964c15a0f14dc23baf40b/osu.Framework.Camera/Graphics/Camera/CameraSprite.cs#L78-L79
However to safely destroy the thread before starting a new one, we need to wait for the execution cycle to end first. Might consider moving some logic to another thread just to end this to make this a non-blocking operation.

**Comment by LeNitrous** [comment]
Did some research and running it asynchronously is the solution. However its a whole can of worms for me to implement it at the moment.

**Comment by sr229** [comment]
Another thing we can do is run this unamanged since I believe GC is causing us problems in this part.

**Comment by sr229** [comment]
@martmists you're assigned here by the way per discussion in Discord.

**Comment by MaryWeeb** [comment]
:flushed:

**Comment by LeNitrous** [comment]
fixed in rewrite
