### ISSUE TITLE
Camera Input has incorrect orientation

### ISSUE THREAD

**Issue by sr229** [vignette-project/osu-framework-camera#6]
If you try to move your head to the left it would look like in the camera input you are going to the right, I assume the frames are flipped which is a bit of an issue.

**Comment by gmlwns2000** [comment]
OpenCV does not use mirror mode by default because they read camera buffer as raw as possible.
So I think it is okay just cv2.flip(1) in capture.read function.

**Comment by LeNitrous** [comment]
We had a discussion regarding this a while back. Since we want to keep the camera module as close as to any camera app out there we might want to flip it.

**Comment by sr229** [comment]
> OpenCV does not use mirror mode by default because they read camera buffer as raw as possible.
> So I think it is okay just cv2.flip(1) in capture.read function.

The problem with that I believe is because the data would reflect incorrect so we definitely need to flip it, though you might need to benchmark to see if there's a massive overhead.

**Comment by gmlwns2000** [comment]
@sr229 
About overhead, it is really tiny, about 1~5ms depends on the device. And also, I think that overhead is good to take because it makes users feel like a normal mirror, so they would think it is more natural.

However, from a data perspective, we should keep aware we used mirror mode, or not.

**Comment by sr229** [comment]
Sounds acceptable in a standpoint. Feel free to patch that up for us @gmlwns2000.

**Comment by sr229** [comment]
This should be fixed now so closing.
