### ISSUE TITLE
System.ArgumentException: The item already exists in this Dropdown

### ISSUE THREAD

**Issue by Fede-26** [vignette-project/osu-framework-camera#9]
When I try to run the `holotrack.Test` project with `dotnet run --project holotrack.Tests/ -v n` it doesn't give me any errors and I can see the webcam and the fact that it tracks my face but not the character animated. (Maybe because it's a test project it isn't implemented here, I don't know).

When I run the `holotrack.Desktop` it compiles succesfully but it gives me the error that the webcam is already in the dropdown list [https://paste.ubuntu.com/p/7wjNSpCgtD/](https://paste.ubuntu.com/p/7wjNSpCgtD/).

If I try to disable the driver of the webcam with `modprobe -r uvcview` it gives the error that it can't find the device `/dev/video0` when I have the device `/dev/video8` active.

It's possible that this issue is related to the strange fact that my sistem creates two device (/dev/video0 and /dev/video1) for a single webcam.

**Comment by sr229** [comment]
As for the character animations, it's already being tracked in https://github.com/vignette-project/vignette/issues/28. As of this time of writing **THE CHARACTER ISN'T HOOKED TO THE LANDMARKS YET.**

It's pretty much implied on Discord we haven't linked anything yet - so please don't test **ahead of time** unless you're planning to actually contribute.
